cert-manager:
  installCRDs: true

prometheus:
  prometheusSpec:
    resources:
      requests.memory: 250Mi
      limits.memory: 500Mi

traefik:
  ports:
    web:
      exposedPort: 7080
    websecure:
      exposedPort: 7443  